### ISSUE TITLE
I had a similar idea, let's talk.

### ISSUE THREAD

**Issue by MichaelTunnell** [enjade-project/enjade-project.github.io#1]
Here is a video I made about my modifications. - https://youtu.be/F1i7jAtHcw4

![](https://i.ytimg.com/vi/F1i7jAtHcw4/maxresdefault.jpg)

I didn't really have any intention of making a project but if you are doing that and you want to use any of my ideas or setups then let me know. I plan to release some how to videos and assets soon as well but they wont be in any kind of packaged project.

**Comment by ubunturox104** [comment]
Have you considered joining us? We've a Telegram group that you can join.
